//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class appropprojectid
    {
        public string projectName { get; set; }
        public string appropProjectId1 { get; set; }
        public Nullable<int> budgetYear { get; set; }
        public string programId { get; set; }
    }
}
