//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPMSDBEntities7 : DbContext
    {
        public SPMSDBEntities7()
            : base("name=SPMSDBEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAppropriationProj> tAppropriationProjs { get; set; }
        public virtual DbSet<tAppropriationProjMFO> tAppropriationProjMFOes { get; set; }
        public virtual DbSet<tAppropriationProjMFOInd> tAppropriationProjMFOInds { get; set; }
        public virtual DbSet<tMFO_perDivision> tMFO_perDivision { get; set; }
        public virtual DbSet<tOffice> tOffices { get; set; }
        public virtual DbSet<tOfficeDivision> tOfficeDivisions { get; set; }
        public virtual DbSet<tProgram> tPrograms { get; set; }
        public virtual DbSet<tProject> tProjects { get; set; }
        public virtual DbSet<tSPMS_CheckListMFO> tSPMS_CheckListMFO { get; set; }
        public virtual DbSet<tSPMS_Classification> tSPMS_Classification { get; set; }
        public virtual DbSet<tSPMS_CommonMFO> tSPMS_CommonMFO { get; set; }
        public virtual DbSet<tSPMS_DPCR> tSPMS_DPCR { get; set; }
        public virtual DbSet<tSPMS_IPCR> tSPMS_IPCR { get; set; }
        public virtual DbSet<tSPMS_IPCR_MPOR> tSPMS_IPCR_MPOR { get; set; }
        public virtual DbSet<tSPMS_IPCR_SMPOR> tSPMS_IPCR_SMPOR { get; set; }
        public virtual DbSet<tSPMS_IPCRRequest> tSPMS_IPCRRequest { get; set; }
        public virtual DbSet<tSPMS_MFOCategory> tSPMS_MFOCategory { get; set; }
        public virtual DbSet<tSPMS_MFOCategoryDesc> tSPMS_MFOCategoryDesc { get; set; }
        public virtual DbSet<tSPMS_MFOStandard> tSPMS_MFOStandard { get; set; }
        public virtual DbSet<tSPMS_OfficeRole> tSPMS_OfficeRole { get; set; }
        public virtual DbSet<tSPMS_OPCR> tSPMS_OPCR { get; set; }
        public virtual DbSet<tSPMS_OTS> tSPMS_OTS { get; set; }
        public virtual DbSet<tSPMS_RequestChange> tSPMS_RequestChange { get; set; }
        public virtual DbSet<tSPMS_Signatories> tSPMS_Signatories { get; set; }
        public virtual DbSet<tSPMS_TargetCountSI> tSPMS_TargetCountSI { get; set; }
        public virtual DbSet<tSPMS_Employees> tSPMS_Employees { get; set; }
        public virtual DbSet<tSPMS_Roles> tSPMS_Roles { get; set; }
        public virtual DbSet<vSPMS_AppropProject> vSPMS_AppropProject { get; set; }
        public virtual DbSet<vSPMS_CheckListMFO> vSPMS_CheckListMFO { get; set; }
        public virtual DbSet<vSPMS_CMFO> vSPMS_CMFO { get; set; }
        public virtual DbSet<vSPMS_CommonMFO> vSPMS_CommonMFO { get; set; }
        public virtual DbSet<vSPMS_DisplayOPCR> vSPMS_DisplayOPCR { get; set; }
        public virtual DbSet<vSPMS_DPCR> vSPMS_DPCR { get; set; }
        public virtual DbSet<vSPMS_Employee> vSPMS_Employee { get; set; }
        public virtual DbSet<vSPMS_Employees> vSPMS_Employees { get; set; }
        public virtual DbSet<vSPMS_IPCR_Request> vSPMS_IPCR_Request { get; set; }
        public virtual DbSet<vSPMS_IPCR_SMPOR> vSPMS_IPCR_SMPOR { get; set; }
        public virtual DbSet<vSPMS_IPCRwCat> vSPMS_IPCRwCat { get; set; }
        public virtual DbSet<vSPMS_LoadDataView> vSPMS_LoadDataView { get; set; }
        public virtual DbSet<vSPMS_MFO_ALL> vSPMS_MFO_ALL { get; set; }
        public virtual DbSet<vSPMS_MFOwCat> vSPMS_MFOwCat { get; set; }
        public virtual DbSet<vSPMS_MPOR> vSPMS_MPOR { get; set; }
        public virtual DbSet<vSPMS_nMFO_ALL> vSPMS_nMFO_ALL { get; set; }
        public virtual DbSet<vSPMS_nOPCR> vSPMS_nOPCR { get; set; }
        public virtual DbSet<vSPMS_OPCR> vSPMS_OPCR { get; set; }
        public virtual DbSet<vSPMS_OpcrStandard> vSPMS_OpcrStandard { get; set; }
        public virtual DbSet<vSPMS_OPCRTable> vSPMS_OPCRTable { get; set; }
        public virtual DbSet<vSPMS_prtOPCR> vSPMS_prtOPCR { get; set; }
        public virtual DbSet<vSPMS_RequestTable> vSPMS_RequestTable { get; set; }
        public virtual DbSet<vSPMS_rOPCRStandard> vSPMS_rOPCRStandard { get; set; }
        public virtual DbSet<vSPMS_showOTS> vSPMS_showOTS { get; set; }
        public virtual DbSet<vSPMSIPCRRating> vSPMSIPCRRatings { get; set; }
        public virtual DbSet<vSPMS_OPCRRating> vSPMS_OPCRRating { get; set; }
    }
}
