//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAppropriationProj
    {
        public int recNo { get; set; }
        public string appropProjectId { get; set; }
        public Nullable<int> budgetYear { get; set; }
        public string projectId { get; set; }
        public string AIPCode { get; set; }
        public string fundSourceId { get; set; }
    }
}
