//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMFO_perDivision
    {
        public int recNo_ { get; set; }
        public string MFOId { get; set; }
        public string DivisionId { get; set; }
        public string division { get; set; }
    }
}
