//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOffice
    {
        public int recNo { get; set; }
        public string officeId { get; set; }
        public string officeCode { get; set; }
        public string officeName { get; set; }
        public string officeNameShort { get; set; }
        public Nullable<int> officeType { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<int> sortNo { get; set; }
    }
}
