//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProject
    {
        public int recNo { get; set; }
        public string projectId { get; set; }
        public Nullable<int> projectIdLF { get; set; }
        public string aipReferenceCode { get; set; }
        public string projectName { get; set; }
        public string programId { get; set; }
        public Nullable<int> functionId { get; set; }
        public string fundSourceId { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
