//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProgram
    {
        public int recNo { get; set; }
        public string programId { get; set; }
        public string aipCode { get; set; }
        public string programName { get; set; }
        public string officeId { get; set; }
        public string functionId { get; set; }
        public string fundSourceId { get; set; }
        public Nullable<int> programTypeId { get; set; }
        public Nullable<int> programIdLF { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
