//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSPMS_IPCRRequest
    {
        public int recNo_ { get; set; }
        public string r_EIC { get; set; }
        public string r_ipcrId { get; set; }
        public Nullable<int> r_Status { get; set; }
        public string r_remarks { get; set; }
    }
}
