//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSPMS_IPCR
    {
        public int recNo_ { get; set; }
        public string r_ipcrId { get; set; }
        public string i_ipcrId { get; set; }
        public string i_EIC { get; set; }
        public string i_MFOId { get; set; }
        public string i_indicatorId { get; set; }
        public Nullable<int> i_target { get; set; }
        public Nullable<int> i_actQuantity { get; set; }
        public string i_actQuality { get; set; }
        public string i_actTimeliness { get; set; }
        public string targetId { get; set; }
        public Nullable<int> i_Rquantity { get; set; }
        public Nullable<int> i_Rquality { get; set; }
        public Nullable<int> i_Rtimeliness { get; set; }
        public Nullable<int> i_category { get; set; }
        public string targetIdparent { get; set; }
    }
}
