//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSPMS_TargetCountSI
    {
        public int recNo { get; set; }
        public string targetId { get; set; }
        public Nullable<int> target { get; set; }
        public string indicatorId { get; set; }
        public string officeId { get; set; }
        public string targetUnit { get; set; }
        public Nullable<int> targetTypeId { get; set; }
        public Nullable<int> tRemaining { get; set; }
        public string divisionId { get; set; }
        public string t_quality { get; set; }
        public string t_timeliness { get; set; }
        public Nullable<int> isShared { get; set; }
        public Nullable<int> isOPCR { get; set; }
    }
}
