//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSPMS_IPCR_MPOR
    {
        public int recNo { get; set; }
        public string ipcrId { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> qtyWk1 { get; set; }
        public Nullable<int> qtyWk2 { get; set; }
        public Nullable<int> qtyWk3 { get; set; }
        public Nullable<int> qtyWk4 { get; set; }
        public Nullable<int> qtyTotal { get; set; }
        public Nullable<int> qlyWk1 { get; set; }
        public Nullable<int> qlyWk2 { get; set; }
        public Nullable<int> qlyWk3 { get; set; }
        public Nullable<int> qlyWk4 { get; set; }
        public Nullable<int> qlyTotal { get; set; }
        public Nullable<double> qlyAve { get; set; }
        public Nullable<int> timeWk1 { get; set; }
        public Nullable<int> timeWk2 { get; set; }
        public Nullable<int> timeWk3 { get; set; }
        public Nullable<int> timeWk4 { get; set; }
        public Nullable<int> timeTotal { get; set; }
        public Nullable<double> timeAve { get; set; }
    }
}
