//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSPMS_RequestChange
    {
        public int recNo { get; set; }
        public string MFOId { get; set; }
        public string indicatorId { get; set; }
        public string reqId { get; set; }
        public string MFO { get; set; }
        public string indicator { get; set; }
        public Nullable<int> target { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> rating { get; set; }
        public string quality { get; set; }
        public string timeliness { get; set; }
        public string date { get; set; }
        public string targetId { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> semester { get; set; }
        public string classificationId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> o_target { get; set; }
        public string o_mfo { get; set; }
        public string o_indicator { get; set; }
        public string o_quality { get; set; }
        public string o_timeliness { get; set; }
        public string o_category { get; set; }
        public string o_year { get; set; }
        public string o_semester { get; set; }
        public string o_classification { get; set; }
    }
}
