//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSPMS_MFOStandard
    {
        public int recNo { get; set; }
        public string targetId { get; set; }
        public string MFOId { get; set; }
        public string indicatorId { get; set; }
        public string rating { get; set; }
        public string quantity { get; set; }
        public string quality { get; set; }
        public string timeliness { get; set; }
    }
}
