//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSPMS_OPCR
    {
        public int recNo { get; set; }
        public string opcrID { get; set; }
        public string indicatorId { get; set; }
        public string officeId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string division { get; set; }
        public string targetId { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> isLocked { get; set; }
    }
}
