//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSPMS_IPCR_Request
    {
        public int recNo_ { get; set; }
        public string r_ipcrId { get; set; }
        public string EIC { get; set; }
        public string F_Name { get; set; }
        public string division { get; set; }
        public Nullable<int> r_Status { get; set; }
        public string divisionName { get; set; }
        public string officeRoleId { get; set; }
        public string positionTitle { get; set; }
    }
}
