//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSPMS_IPCR_SMPOR
    {
        public int recNo_ { get; set; }
        public string i_EIC { get; set; }
        public string i_MFOId { get; set; }
        public string CLDesc { get; set; }
        public string MFO { get; set; }
        public Nullable<int> i_target { get; set; }
        public string i_indicatorId { get; set; }
        public Nullable<int> i_category { get; set; }
        public string description { get; set; }
        public string F_Name { get; set; }
        public string divisionName { get; set; }
        public string officeName { get; set; }
        public string officeNameShort { get; set; }
        public string officeRoleId { get; set; }
        public string positionTitle { get; set; }
        public string division { get; set; }
        public string smporId { get; set; }
        public string ipcrId { get; set; }
        public Nullable<double> qty_mFirst { get; set; }
        public Nullable<double> qty_mSecond { get; set; }
        public Nullable<double> qty_mThird { get; set; }
        public Nullable<double> qty_mFourth { get; set; }
        public Nullable<double> qty_mFifth { get; set; }
        public Nullable<double> qty_mSixth { get; set; }
        public Nullable<double> qty_total { get; set; }
        public Nullable<double> qty_rating { get; set; }
        public Nullable<double> qly_mFirst { get; set; }
        public Nullable<double> qly_mSecond { get; set; }
        public Nullable<double> qly_mThird { get; set; }
        public Nullable<double> qly_mFourth { get; set; }
        public Nullable<double> qly_mFifth { get; set; }
        public Nullable<double> qly_mSixth { get; set; }
        public Nullable<double> qly_total { get; set; }
        public Nullable<double> qly_rating { get; set; }
        public Nullable<double> time_mFirst { get; set; }
        public Nullable<double> time_mSecond { get; set; }
        public Nullable<double> time_mThird { get; set; }
        public Nullable<double> time_mFourth { get; set; }
        public Nullable<double> time_mFifth { get; set; }
        public Nullable<double> time_mSixth { get; set; }
        public Nullable<double> time_total { get; set; }
        public Nullable<double> time_rating { get; set; }
        public string r_ipcrId { get; set; }
        public Nullable<int> r_year { get; set; }
        public Nullable<int> r_semester { get; set; }
    }
}
