//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSPMS_Employee
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string idNo { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public string fullNameTitle { get; set; }
        public string sex { get; set; }
        public string officeRoleId { get; set; }
        public string positionTitle { get; set; }
        public string divisionId { get; set; }
        public string divisionName { get; set; }
        public string officeId { get; set; }
        public string officeCode { get; set; }
        public string officeName { get; set; }
        public string officeNameShort { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
