//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSPMS_EmployeeSignatories
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string F_Name { get; set; }
        public string officeRoleId { get; set; }
        public string positionTitle { get; set; }
        public string division { get; set; }
        public string supervisorId { get; set; }
        public string officeheadId { get; set; }
        public string supervisorName { get; set; }
        public string officeheadName { get; set; }
        public string description { get; set; }
        public string divisionName { get; set; }
        public string officeId { get; set; }
        public string officeName { get; set; }
        public string officeNameShort { get; set; }
    }
}
