//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSPMSIPCRRating
    {
        public int recNo { get; set; }
        public string controlNo { get; set; }
        public string EIC { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public string positionTitle { get; set; }
        public string subPositionTitle { get; set; }
        public Nullable<decimal> ratingNum { get; set; }
        public string ratingAdj { get; set; }
        public Nullable<int> semester { get; set; }
        public Nullable<int> year { get; set; }
        public string details { get; set; }
        public Nullable<int> tag { get; set; }
        public string remarks { get; set; }
        public string encoderEIC { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
    }
}
