//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSPMS_prtOPCR
    {
        public string description { get; set; }
        public string officeId { get; set; }
        public string programId { get; set; }
        public Nullable<int> programTypeId { get; set; }
        public string projectId { get; set; }
        public string appropProjectId { get; set; }
        public string MFOId { get; set; }
        public string MFO { get; set; }
        public string indicatorId { get; set; }
        public Nullable<int> target { get; set; }
        public string indicator { get; set; }
        public string officeNameShort { get; set; }
        public Nullable<int> isActive { get; set; }
    }
}
