//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSPMS_OPCRRating
    {
        public int recNo { get; set; }
        public string opcrID { get; set; }
        public string officeId { get; set; }
        public string MFO { get; set; }
        public string indicator { get; set; }
        public Nullable<int> target { get; set; }
        public string targetUnit { get; set; }
        public Nullable<int> tRemaining { get; set; }
        public Nullable<double> r_qty { get; set; }
        public Nullable<double> r_qly { get; set; }
        public Nullable<double> r_time { get; set; }
        public Nullable<double> tCommittedQuantity { get; set; }
        public Nullable<double> qty_rating { get; set; }
        public Nullable<double> qly_rating { get; set; }
        public Nullable<double> time_rating { get; set; }
    }
}
