//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSPMS_showOTS
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string MFOId { get; set; }
        public string MFO { get; set; }
        public string indicator { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> isCMFO { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> semester { get; set; }
        public string classificationId { get; set; }
        public string description { get; set; }
        public Nullable<int> target { get; set; }
        public string indicatorId { get; set; }
        public string officeId { get; set; }
        public Nullable<int> r_quantity { get; set; }
        public Nullable<int> r_quality { get; set; }
        public Nullable<int> r_timeliness { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string approvedby { get; set; }
        public Nullable<int> status { get; set; }
        public string targetId { get; set; }
        public Nullable<int> i_actQuantity { get; set; }
        public string i_actQuality { get; set; }
        public string i_actTimeliness { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> month { get; set; }
    }
}
