//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSPMS_EmployeeAccountRoles
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string F_Name { get; set; }
        public string division { get; set; }
        public string RID { get; set; }
        public string R_Description { get; set; }
        public string officeRoleId { get; set; }
        public string positionTitle { get; set; }
    }
}
