//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models.SPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSPMS_IPCRwCat
    {
        public int recNo_ { get; set; }
        public string r_ipcrId { get; set; }
        public string i_ipcrId { get; set; }
        public string i_EIC { get; set; }
        public string i_MFOId { get; set; }
        public string i_indicatorId { get; set; }
        public string indicator { get; set; }
        public Nullable<int> i_target { get; set; }
        public string CLId { get; set; }
        public string CLDesc { get; set; }
        public string CL_MFOId { get; set; }
        public string MFO { get; set; }
        public string officeId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string description { get; set; }
        public string divisionId { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> semester { get; set; }
        public Nullable<int> i_actQuantity { get; set; }
        public string Expr1 { get; set; }
        public string targetId { get; set; }
        public Nullable<int> i_category { get; set; }
        public string targetIdparent { get; set; }
        public Nullable<int> tRemaining { get; set; }
        public Nullable<int> r_Status { get; set; }
        public string F_Name { get; set; }
        public string officeName { get; set; }
        public string officeNameShort { get; set; }
        public string divisionName { get; set; }
    }
}
