//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tApplicantEligibility
    {
        public int recNo { get; set; }
        public string eligibilityId { get; set; }
        public string applicantCode { get; set; }
        public string eligibilityCode { get; set; }
        public string eligibilityName { get; set; }
        public Nullable<decimal> rating { get; set; }
        public Nullable<System.DateTime> examDate { get; set; }
        public string examPlace { get; set; }
        public string licenseNo { get; set; }
        public Nullable<System.DateTime> validityDate { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public string eligibilityNo { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
