//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tApplicantProfile
    {
        public int recNo { get; set; }
        public string applicationCode { get; set; }
        public string itemLevel { get; set; }
        public string education { get; set; }
        public string experience { get; set; }
        public string training { get; set; }
        public string eligibility { get; set; }
        public string performanceRating { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
