//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tApplicant
    {
        public int recNo { get; set; }
        public string applicantCode { get; set; }
        public string EIC { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string birthPlace { get; set; }
        public string sex { get; set; }
        public string mobileNo { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string verificationCode { get; set; }
        public Nullable<bool> isVerified { get; set; }
        public string userEIC { get; set; }
    }
}
