//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPApplication
    {
        public int recNo { get; set; }
        public string applicationCode { get; set; }
        public string EIC { get; set; }
        public string applicantCode { get; set; }
        public string publicationItemCode { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public Nullable<int> appTypeCode { get; set; }
        public Nullable<int> tag { get; set; }
        public string remarks { get; set; }
        public Nullable<int> isComplete { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
