//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPApplication
    {
        public int recNo { get; set; }
        public string applicationCode { get; set; }
        public string EIC { get; set; }
        public string applicantCode { get; set; }
        public string applicantName { get; set; }
        public string applicantNameLast { get; set; }
        public string applicantPositionTitle { get; set; }
        public string applicantSubPositionTitle { get; set; }
        public Nullable<int> applicantSalaryGrade { get; set; }
        public Nullable<int> applicantStep { get; set; }
        public string publicationCode { get; set; }
        public string publicationItemCode { get; set; }
        public string plantillaCode { get; set; }
        public Nullable<int> itemNo { get; set; }
        public string positionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<decimal> rateMonth { get; set; }
        public string QSEducation { get; set; }
        public string QSExperience { get; set; }
        public string QSTraining { get; set; }
        public string QSEligibility { get; set; }
        public string QSNotation { get; set; }
        public string departmentCode { get; set; }
        public string departmentName { get; set; }
        public string placeOfAssignment { get; set; }
        public Nullable<int> appTypeCode { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<System.DateTime> CSCPostedDate { get; set; }
        public Nullable<System.DateTime> CSCClosingDate { get; set; }
        public Nullable<System.DateTime> PSBDate { get; set; }
        public Nullable<int> publicationItemTag { get; set; }
        public string employmentStatus { get; set; }
        public string employmentStatusNameShort { get; set; }
        public string employmentStatusTag { get; set; }
    }
}
