//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPEmployeeList
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string idNo { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public string fullNameTitle { get; set; }
        public string namePrefix { get; set; }
        public string nameSuffix { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string birthPlace { get; set; }
        public string sex { get; set; }
        public string civilStatCode { get; set; }
        public string plantillaCode { get; set; }
        public string positionCode { get; set; }
        public string positionTitle { get; set; }
        public string subPositionCode { get; set; }
        public string subPositionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<decimal> salaryRate { get; set; }
        public string salaryType { get; set; }
        public string salaryDetailCode { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatus { get; set; }
        public string employmentStatusNameShort { get; set; }
        public string employmentStatusTag { get; set; }
        public Nullable<int> isPlantilla { get; set; }
        public Nullable<int> isGovService { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string bloodType { get; set; }
        public string GSISIDNo { get; set; }
        public string BPNo { get; set; }
        public string HDMFNo { get; set; }
        public string HDMFMID { get; set; }
        public string PHICNo { get; set; }
        public string SSSNo { get; set; }
        public string TINNo { get; set; }
        public string citizenship { get; set; }
        public string houseBlockNoResAddress { get; set; }
        public string streetResAddress { get; set; }
        public string subdivisionResAddress { get; set; }
        public string brgyResAddress { get; set; }
        public string cityMunResAddress { get; set; }
        public string provinceResAddress { get; set; }
        public string ZIPResAddress { get; set; }
        public string houseBlockNoPermAddress { get; set; }
        public string streetPermAddress { get; set; }
        public string subdivisionPermAddress { get; set; }
        public string brgyPermAddress { get; set; }
        public string cityMunPermAddress { get; set; }
        public string provincePermAddress { get; set; }
        public string ZIPPermAddress { get; set; }
        public string completeAddress { get; set; }
        public string telephoneNo { get; set; }
        public string mobileNo { get; set; }
        public Nullable<int> isMobileVerified { get; set; }
        public Nullable<System.DateTime> idDDNIssuedDate { get; set; }
        public string emailAddress { get; set; }
        public Nullable<System.DateTime> dateOrigAppointment { get; set; }
        public Nullable<System.DateTime> dateLastPromoted { get; set; }
        public string workGroupCode { get; set; }
        public string workGroupName { get; set; }
        public Nullable<int> tag { get; set; }
        public string fundSourceCode { get; set; }
        public string projectName { get; set; }
        public string transCode { get; set; }
        public Nullable<int> isActivePosition { get; set; }
        public Nullable<System.DateTime> periodTo { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public string appointmentItemCode { get; set; }
    }
}
