//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSysMenu
    {
        public string menuCode { get; set; }
        public string menuName { get; set; }
        public string controllerName { get; set; }
        public string methodName { get; set; }
        public Nullable<int> menuTypeNo { get; set; }
        public Nullable<int> orderNo { get; set; }
        public string menuGroupCode { get; set; }
        public string groupName { get; set; }
        public string fontIcon { get; set; }
        public Nullable<int> groupOrderNo { get; set; }
        public Nullable<int> groupTag { get; set; }
        public string menuSubGroupCode { get; set; }
        public string subGroupName { get; set; }
        public string subFontIcon { get; set; }
        public Nullable<int> subOrderNo { get; set; }
        public Nullable<int> subGroupTag { get; set; }
        public Nullable<int> tag { get; set; }
        public string linkIcon { get; set; }
    }
}
