//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aaTable
    {
        public int no { get; set; }
        public string emp_idno { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string nameext { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string tin { get; set; }
        public string gsisid { get; set; }
        public string gsisbpno { get; set; }
        public string policyno { get; set; }
        public string hdmfid { get; set; }
        public string hdmfmid { get; set; }
        public string philhid { get; set; }
    }
}
