//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRISEntities : DbContext
    {
        public HRISEntities()
            : base("name=HRISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAttShiftingEmpScheme> tAttShiftingEmpSchemes { get; set; }
        public virtual DbSet<tapp212FamilyBackground> tapp212FamilyBackground { get; set; }
        public virtual DbSet<tapp212EducLevel> tapp212EducLevel { get; set; }
        public virtual DbSet<tapp212EducBackground> tapp212EducBackground { get; set; }
        public virtual DbSet<tapp212Trainings> tapp212Trainings { get; set; }
        public virtual DbSet<tappEmployee> tappEmployees { get; set; }
        public virtual DbSet<tAttDailyLog> tAttDailyLogs { get; set; }
    }
}
