//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tApplicantIPCR
    {
        public int recNo { get; set; }
        public string applicantCode { get; set; }
        public Nullable<decimal> NR { get; set; }
        public string AR { get; set; }
        public int year { get; set; }
        public int sem { get; set; }
        public Nullable<bool> canEdit { get; set; }
    }
}
