//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tapp212EducBackground
    {
        public int fRecNo { get; set; }
        public string fContrlNo { get; set; }
        public string fLevelTag { get; set; }
        public string fSchoolName { get; set; }
        public string fDegree { get; set; }
        public string fCorsCateg { get; set; }
        public string fYearGrad { get; set; }
        public string fHighLevel { get; set; }
        public string fFromDT { get; set; }
        public string fToDT { get; set; }
        public string fHonors { get; set; }
        public string fRemarks { get; set; }
        public string fHighestEduc { get; set; }
        public string fCAV { get; set; }
        public string fUser { get; set; }
        public string fIncludeTag { get; set; }
        public string EIC { get; set; }
        public Nullable<int> isApproved { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public string approvedEIC { get; set; }
    }
}
