//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tApplicantEducation
    {
        public int recNo { get; set; }
        public string applicantCode { get; set; }
        public string schoolLevelCode { get; set; }
        public string schoolName { get; set; }
        public string degree { get; set; }
        public string yearGraduated { get; set; }
        public string highestLevel { get; set; }
        public Nullable<int> yearFrom { get; set; }
        public Nullable<int> yearTo { get; set; }
        public string academicHonor { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public string educationNo { get; set; }
    }
}
