//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tapp212FamilyBackground
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string fPaSName { get; set; }
        public string fPaFName { get; set; }
        public string fPaMidName { get; set; }
        public string fPaExtn { get; set; }
        public string fMaMaiden { get; set; }
        public string fMaSname { get; set; }
        public string fMaFName { get; set; }
        public string fMaMidName { get; set; }
        public Nullable<int> isApproved { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public string approvedEIC { get; set; }
        public string fUser { get; set; }
    }
}
