//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tapp212Trainings
    {
        public int fRecNo { get; set; }
        public string ID_no { get; set; }
        public string fTitle { get; set; }
        public Nullable<System.DateTime> fFromDT { get; set; }
        public string ftoDT { get; set; }
        public string fHoursNo { get; set; }
        public string fConducted { get; set; }
        public string fVenue { get; set; }
        public string fTrainClas { get; set; }
        public string fTrainType { get; set; }
        public string fGroupTag { get; set; }
        public string fDateEncod { get; set; }
        public string fUser { get; set; }
        public string EIC { get; set; }
        public Nullable<int> isApproved { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public string approvedEIC { get; set; }
    }
}
