//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAttWorkSched
    {
        public int recNo { get; set; }
        public string workSchedId { get; set; }
        public string workSchedName { get; set; }
        public string details { get; set; }
        public Nullable<System.DateTime> workSchedMonth { get; set; }
        public Nullable<int> period { get; set; }
        public string remarks { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public string userEIC { get; set; }
    }
}
