//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAttEmpDailyLog
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public Nullable<System.DateTime> logDate { get; set; }
        public Nullable<System.DateTime> login { get; set; }
        public Nullable<System.DateTime> logout { get; set; }
        public string shiftTemplateId { get; set; }
    }
}
