//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAttShiftingEmpScheme
    {
        public int recNo { get; set; }
        public string controlNo { get; set; }
        public string EIC { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
        public Nullable<System.DateTime> In1 { get; set; }
        public Nullable<System.DateTime> Out1 { get; set; }
        public Nullable<System.DateTime> In2 { get; set; }
        public Nullable<System.DateTime> Out2 { get; set; }
        public Nullable<int> isApproved { get; set; }
        public string approvedEIC { get; set; }
        public string encoderEIC { get; set; }
        public string remarks { get; set; }
        public Nullable<int> isNoBreak { get; set; }
        public Nullable<int> returnTag { get; set; }
    }
}
