//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAttLogDevice
    {
        public int recNo { get; set; }
        public string deviceID { get; set; }
        public string deviceName { get; set; }
        public string IP { get; set; }
        public string details { get; set; }
        public string deviceMAC { get; set; }
        public string deviceSN { get; set; }
        public Nullable<int> lastRecNoLog { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
