//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAttLog
    {
        public int recNo { get; set; }
        public Nullable<int> userLogNo { get; set; }
        public string EIC { get; set; }
        public Nullable<System.DateTime> logDT { get; set; }
        public string deviceID { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<int> isActive { get; set; }
    }
}
