//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLNDComptAssessmentGroup
    {
        public int recNo { get; set; }
        public string assmntGroupCode { get; set; }
        public string assmntGroupName { get; set; }
        public string assmntGroupDesc { get; set; }
        public Nullable<int> assmntGroupTag { get; set; }
    }
}
