//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLNDCompetencyGroup
    {
        public string comptGroupCode { get; set; }
        public string comptGroupName { get; set; }
        public Nullable<int> orderNo { get; set; }
    }
}
