//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLNDPsychoSocial
    {
        public int recNo { get; set; }
        public string psychoCode { get; set; }
        public string question { get; set; }
        public Nullable<int> groupTag { get; set; }
        public Nullable<int> orderNo { get; set; }
    }
}
