//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLNDComptAssessment
    {
        public int recNo { get; set; }
        public string assessmentCode { get; set; }
        public string assessmentName { get; set; }
        public string assessmentDetail { get; set; }
        public Nullable<int> assessmentType { get; set; }
        public string comptPositionCode { get; set; }
        public string assmntGroupCode { get; set; }
        public string publicationItemCode { get; set; }
        public Nullable<int> tag { get; set; }
        public string userEIC { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
    }
}
