//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLNDSurveyReport
    {
        public int recNo { get; set; }
        public string fullNameLast { get; set; }
        public string positionTitle { get; set; }
        public string BSDC { get; set; }
        public string SDCT1 { get; set; }
        public string SDCT2 { get; set; }
        public Nullable<int> levelNo { get; set; }
        public string remarks { get; set; }
        public string reportId { get; set; }
    }
}
