//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLNDComptCriteria
    {
        public int standardNo { get; set; }
        public Nullable<int> basic { get; set; }
        public Nullable<int> intermediate { get; set; }
        public Nullable<int> advanced { get; set; }
        public Nullable<int> superior { get; set; }
    }
}
