//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOnlineService
    {
        public int recNo { get; set; }
        public string onlineServiceID { get; set; }
        public string onlineServiceName { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> serviceProviderTag { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
