//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOnlineRequest
    {
        public int recNo { get; set; }
        public string requestID { get; set; }
        public string EIC { get; set; }
        public string idNo { get; set; }
        public string purpose { get; set; }
        public string position { get; set; }
        public string workStatus { get; set; }
        public string officeCode { get; set; }
        public string officeName { get; set; }
        public string remarks { get; set; }
        public Nullable<int> serviceProviderTag { get; set; }
        public string etracsObjID { get; set; }
        public Nullable<int> requestTag { get; set; }
    }
}
