//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPDSWE
    {
        public int recNo { get; set; }
        public string WESCode { get; set; }
        public string EIC { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public string positionTitle { get; set; }
        public string officeName { get; set; }
        public string supervisor { get; set; }
        public string agencyName { get; set; }
        public string actualDuties { get; set; }
    }
}
