//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPDSReference
    {
        public int recNo { get; set; }
        public string controlNo { get; set; }
        public string EIC { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string telNo { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
