//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPDSProfile
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string spouseLastName { get; set; }
        public string spouseFirstName { get; set; }
        public string spouseMiddleName { get; set; }
        public string spouseExtnName { get; set; }
        public string spouseOccupation { get; set; }
        public string spouseEmployeerName { get; set; }
        public string spouseEmployeerAddrs { get; set; }
        public string spouseEmployeerTelNo { get; set; }
        public string fatherLastName { get; set; }
        public string fatherFirstName { get; set; }
        public string fatherMidddleName { get; set; }
        public string fatherExtnName { get; set; }
        public string motherLastName { get; set; }
        public string motherFirstName { get; set; }
        public string motherMiddleName { get; set; }
        public Nullable<int> citizenship { get; set; }
        public Nullable<int> citizenshipType { get; set; }
        public string citizenshipCountry { get; set; }
        public string addrsResHouseBlk { get; set; }
        public string addrsResStreet { get; set; }
        public string addrsResVillage { get; set; }
        public string addrsResBrgyCode { get; set; }
        public string addrsResBarangay { get; set; }
        public string addrsResCityMun { get; set; }
        public string addrsResProvince { get; set; }
        public string addrsResZip { get; set; }
        public string addrsPermHouseBlk { get; set; }
        public string addrsPermStreet { get; set; }
        public string addrsPermVillage { get; set; }
        public string addrsPermBrgyCode { get; set; }
        public string addrsPermBarangay { get; set; }
        public string addrsPermCityMun { get; set; }
        public string addrsPermProvince { get; set; }
        public string addrsPermZip { get; set; }
        public Nullable<int> infoDegreeThird { get; set; }
        public Nullable<int> infoDegreeFourth { get; set; }
        public string infoDegreeFourthDetails { get; set; }
        public Nullable<int> infoAdminOffense { get; set; }
        public string infoAdminOffenseDetails { get; set; }
        public Nullable<int> infoCriminalCharge { get; set; }
        public Nullable<System.DateTime> infoCriminalChargeFileDate { get; set; }
        public string infoCriminalChageCaseStatus { get; set; }
        public Nullable<int> infoConvicted { get; set; }
        public string infoConvictedDetails { get; set; }
        public Nullable<int> infoHasSeparatedService { get; set; }
        public string infoHasSeparatedServiceDetails { get; set; }
        public Nullable<int> infoIsCandidate { get; set; }
        public string infoIsCandidateDetails { get; set; }
        public Nullable<int> infoHasGovtResigned { get; set; }
        public string infoHasGovtResignedDetails { get; set; }
        public Nullable<int> infoHasImmigrant { get; set; }
        public string infoHasImmigrantDetails { get; set; }
        public Nullable<int> infoIndigenous { get; set; }
        public string infoIndigenousDetails { get; set; }
        public Nullable<int> infoPWD { get; set; }
        public string infoPWDDetails { get; set; }
        public Nullable<int> infoSoloParent { get; set; }
        public string infoSoloParentDetails { get; set; }
        public string govtIssuedId { get; set; }
        public string govtIssuedIdNo { get; set; }
        public string govtIssuedDatePlace { get; set; }
    }
}
