//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPDSTraining
    {
        public int recNo { get; set; }
        public string controlNo { get; set; }
        public string EIC { get; set; }
        public string trainingTitle { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public Nullable<int> hoursNo { get; set; }
        public string trainingTypeCode { get; set; }
        public string conductedBy { get; set; }
        public Nullable<int> isVerified { get; set; }
        public string verifiedByEIC { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public Nullable<int> pageNo { get; set; }
        public string versionTransNo { get; set; }
    }
}
