//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRefAdrsCityMun
    {
        public int recNo { get; set; }
        public string cityMunCode { get; set; }
        public string cityMunName { get; set; }
        public string provCode { get; set; }
    }
}
