//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReportPlantilla
    {
        public int recNo { get; set; }
        public Nullable<int> budgetYear { get; set; }
        public string functionCode { get; set; }
        public Nullable<int> oldItemNo { get; set; }
        public Nullable<int> itemNo { get; set; }
        public string positionTitle { get; set; }
        public string subPositionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<decimal> currentYearRate { get; set; }
        public Nullable<decimal> proposedYearRate { get; set; }
        public string positionLevel { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extnName { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string eligibility { get; set; }
        public Nullable<System.DateTime> dateOrigAppointment { get; set; }
        public Nullable<System.DateTime> dateLastPromoted { get; set; }
        public string statusName { get; set; }
        public string remarks { get; set; }
        public string clusterCode { get; set; }
        public string clusterName { get; set; }
        public string divisionCode { get; set; }
        public string divisionName { get; set; }
        public string sectionCode { get; set; }
        public string sectionName { get; set; }
        public string unitCode { get; set; }
        public string unitName { get; set; }
        public Nullable<int> pageNo { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> keyPositionTag { get; set; }
        public string statTag { get; set; }
    }
}
