//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPPositionQ
    {
        public int recNo { get; set; }
        public string plantillaCode { get; set; }
        public string QSEducation { get; set; }
        public string QSExperience { get; set; }
        public string QSTraining { get; set; }
        public string QSEligibility { get; set; }
        public string QSEligibilityPub { get; set; }
        public string QSNotation { get; set; }
    }
}
