//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPZPSChecker
    {
        public int recNo { get; set; }
        public string appointmentItemCode { get; set; }
        public Nullable<decimal> currentPS { get; set; }
        public Nullable<decimal> counterPS { get; set; }
    }
}
