//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPServiceRecord
    {
        public long recNo { get; set; }
        public string transCode { get; set; }
        public string EIC { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public string dateToText { get; set; }
        public string positionTitle { get; set; }
        public string employmentStatus { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string salaryType { get; set; }
        public string placeOfAssignment { get; set; }
        public string branch { get; set; }
        public string LWOP { get; set; }
        public string separationCause { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public string userEIC { get; set; }
        public Nullable<int> loyaltyTag { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<int> isSysGen { get; set; }
    }
}
