//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPPSBSchedule
    {
        public int recNo { get; set; }
        public string transCode { get; set; }
        public string publicationItemCode { get; set; }
        public Nullable<int> itemCount { get; set; }
        public string itemText { get; set; }
        public Nullable<System.DateTime> PSBDate { get; set; }
        public string venue { get; set; }
        public string remarks { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public string userEIC { get; set; }
    }
}
