//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPVacantPositionSum
    {
        public int recNo { get; set; }
        public string reportCode { get; set; }
        public string functionCode { get; set; }
        public string functionName { get; set; }
        public Nullable<int> levelFirst { get; set; }
        public Nullable<int> levelSecond { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<System.DateTime> reportDT { get; set; }
    }
}
