//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPPlantilla
    {
        public int recNo { get; set; }
        public string plantillaCode { get; set; }
        public Nullable<int> oldItemNo { get; set; }
        public Nullable<int> newItemNo { get; set; }
        public Nullable<int> tmpItemNo { get; set; }
        public string structureCode { get; set; }
        public string positionCode { get; set; }
        public string subPositionCode { get; set; }
        public Nullable<bool> isFunded { get; set; }
        public Nullable<int> fundStat { get; set; }
        public string employmentStatusCode { get; set; }
        public string magnaCode { get; set; }
        public Nullable<int> refNo { get; set; }
        public Nullable<int> QSJDTag { get; set; }
        public string functionCode { get; set; }
        public Nullable<int> pageNo { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> hazardCode { get; set; }
    }
}
