//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPEmployee
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string idNo { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public string fullNameTitle { get; set; }
        public string namePrefix { get; set; }
        public string nameSuffix { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string birthPlace { get; set; }
        public string sex { get; set; }
        public string civilStatCode { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string bloodType { get; set; }
        public string GSISIDNo { get; set; }
        public string BPNo { get; set; }
        public string GSISPolicyNo { get; set; }
        public string HDMFNo { get; set; }
        public string HDMFMID { get; set; }
        public string PHICNo { get; set; }
        public string SSSNo { get; set; }
        public string TINNo { get; set; }
        public string citizenship { get; set; }
        public string houseBlockNoResAddress { get; set; }
        public string streetResAddress { get; set; }
        public string subdivisionResAddress { get; set; }
        public string brgyResAddress { get; set; }
        public string cityMunResAddress { get; set; }
        public string provinceResAddress { get; set; }
        public string ZIPResAddress { get; set; }
        public string houseBlockNoPermAddress { get; set; }
        public string streetPermAddress { get; set; }
        public string subdivisionPermAddress { get; set; }
        public string brgyPermAddress { get; set; }
        public string cityMunPermAddress { get; set; }
        public string provincePermAddress { get; set; }
        public string ZIPPermAddress { get; set; }
        public string completeAddress { get; set; }
        public string telephoneNo { get; set; }
        public string mobileNo { get; set; }
        public Nullable<int> isMobileVerified { get; set; }
        public Nullable<System.DateTime> idDDNIssuedDate { get; set; }
        public string emailAddress { get; set; }
        public Nullable<System.DateTime> dateOrigAppointment { get; set; }
        public Nullable<System.DateTime> dateLastPromoted { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
