//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPPSBApp
    {
        public int recNo { get; set; }
        public string appointmentCode { get; set; }
        public string applicationCode { get; set; }
        public string plantillaCode { get; set; }
        public string EIC { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<System.DateTime> psbDate { get; set; }
    }
}
