//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPRPTRAI
    {
        public int recNo { get; set; }
        public string RAICode { get; set; }
        public string RAIName { get; set; }
        public Nullable<System.DateTime> RAIDate { get; set; }
        public Nullable<int> RAIStat { get; set; }
        public Nullable<int> itemCount { get; set; }
        public string appointmentCode { get; set; }
        public string userEIC { get; set; }
        public Nullable<System.DateTime> validatedDate { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<int> chkList_ApptForms { get; set; }
        public Nullable<int> chkList_Casual { get; set; }
        public Nullable<int> chkList_PDS { get; set; }
        public Nullable<int> chkList_Eligibility { get; set; }
        public Nullable<int> chkList_PDF { get; set; }
        public Nullable<int> chkList_Oath { get; set; }
        public Nullable<int> chkList_Assumption { get; set; }
    }
}
