//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPApplicationProfile
    {
        public int recNo { get; set; }
        public string applicationCode { get; set; }
        public string itemLevel { get; set; }
        public string particulars { get; set; }
        public Nullable<decimal> rating { get; set; }
        public string profileCode { get; set; }
        public Nullable<int> orderNo { get; set; }
        public string userEIC { get; set; }
    }
}
