//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPRefFundPersonnelService
    {
        public long recNo { get; set; }
        public string PSId { get; set; }
        public string EIC { get; set; }
        public string positionCode { get; set; }
        public string employmentStatusCode { get; set; }
        public Nullable<System.DateTime> periodFrom { get; set; }
        public Nullable<System.DateTime> periodTo { get; set; }
        public string rateType { get; set; }
        public Nullable<decimal> dailyRate { get; set; }
        public Nullable<decimal> monthlyRate { get; set; }
        public Nullable<decimal> annualRate { get; set; }
        public Nullable<decimal> PERA { get; set; }
        public Nullable<decimal> earnedLeave { get; set; }
        public Nullable<decimal> RA { get; set; }
        public Nullable<decimal> TA { get; set; }
        public Nullable<decimal> hazard { get; set; }
        public Nullable<decimal> laundry { get; set; }
        public Nullable<decimal> subs { get; set; }
        public Nullable<decimal> bonusMY { get; set; }
        public Nullable<decimal> bonusYE { get; set; }
        public Nullable<decimal> cashGift { get; set; }
        public Nullable<decimal> clothing { get; set; }
        public Nullable<decimal> loyalty { get; set; }
        public Nullable<decimal> gsis { get; set; }
        public Nullable<decimal> ecc { get; set; }
        public Nullable<decimal> hdmf { get; set; }
        public Nullable<decimal> phic { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> monthCount { get; set; }
        public string fundSourceCode { get; set; }
        public string userId { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public string remarks { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
