//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPApplicationAssessment
    {
        public int recNo { get; set; }
        public string applicationCode { get; set; }
        public Nullable<decimal> performanceRating { get; set; }
        public Nullable<decimal> performanceScore { get; set; }
        public Nullable<decimal> comptAssmentRating { get; set; }
        public Nullable<decimal> comptAssmentScore { get; set; }
        public Nullable<decimal> beiRating { get; set; }
        public Nullable<decimal> beiScore { get; set; }
        public Nullable<decimal> psychoRating { get; set; }
        public Nullable<decimal> psychoScore { get; set; }
        public Nullable<decimal> educationScore { get; set; }
        public Nullable<decimal> experienceScore { get; set; }
        public Nullable<decimal> trainingScore { get; set; }
        public Nullable<decimal> eligibilityScore { get; set; }
        public Nullable<decimal> awardScore { get; set; }
        public Nullable<decimal> totalScore { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
