//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPZPersonnelService
    {
        public int recNo { get; set; }
        public string appointmentItemCode { get; set; }
        public string appointmentCode { get; set; }
        public string positionTitle { get; set; }
        public Nullable<decimal> dailyRate { get; set; }
        public Nullable<decimal> monthlyRate { get; set; }
        public Nullable<decimal> annualRate { get; set; }
        public Nullable<decimal> PERA { get; set; }
        public Nullable<decimal> leaveEarned { get; set; }
        public Nullable<decimal> hazardPay { get; set; }
        public Nullable<decimal> subsistence { get; set; }
        public Nullable<decimal> laundry { get; set; }
        public Nullable<decimal> midYearBonus { get; set; }
        public Nullable<decimal> yearEndBonus { get; set; }
        public Nullable<decimal> cashGift { get; set; }
        public Nullable<decimal> lifeRetmnt { get; set; }
        public Nullable<decimal> ECC { get; set; }
        public Nullable<decimal> hdmf { get; set; }
        public Nullable<decimal> phic { get; set; }
        public Nullable<decimal> clothing { get; set; }
        public Nullable<decimal> total { get; set; }
        public string userID { get; set; }
        public Nullable<System.DateTime> periodFrom { get; set; }
        public Nullable<System.DateTime> periodTo { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public Nullable<int> PSTag { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
