//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPSalaryTable
    {
        public int recNo { get; set; }
        public string salaryCode { get; set; }
        public int year { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string remarks { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
