//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPPositionContract
    {
        public int recNo { get; set; }
        public string positionCode { get; set; }
        public string positionTitle { get; set; }
        public string positionDesc { get; set; }
        public string shortPositionTitle { get; set; }
        public string positionType { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string salaryTypeCode { get; set; }
        public Nullable<int> isActive { get; set; }
    }
}
