//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPRefFundAppr
    {
        public int recNo { get; set; }
        public string appropriationCode { get; set; }
        public string approNo { get; set; }
        public Nullable<int> approYear { get; set; }
        public Nullable<int> budgetYear { get; set; }
    }
}
