//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPZPlantillaCurrent
    {
        public int recNo { get; set; }
        public string structureCode { get; set; }
        public string structureName { get; set; }
        public Nullable<int> structureNo { get; set; }
        public Nullable<int> structSortNo { get; set; }
        public string functionCode { get; set; }
        public string plantillaCode { get; set; }
        public string oldItemNo { get; set; }
        public string itemNo { get; set; }
        public string positionTitle { get; set; }
        public string subPositionTitle { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<decimal> annualAuthorize { get; set; }
        public Nullable<decimal> annualActual { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public string positionLevel { get; set; }
        public Nullable<int> isFunded { get; set; }
        public string EIC { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extname { get; set; }
        public string fullNameLast { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string eligibility { get; set; }
        public Nullable<System.DateTime> origApptDate { get; set; }
        public Nullable<System.DateTime> lastPromDate { get; set; }
        public string empStatus { get; set; }
        public string remarks { get; set; }
        public string clusterCode { get; set; }
        public string clusterName { get; set; }
        public string divisionCode { get; set; }
        public string divisionName { get; set; }
        public string sectionCode { get; set; }
        public string sectionName { get; set; }
        public string unitCode { get; set; }
        public string unitName { get; set; }
        public Nullable<int> plantillaNo { get; set; }
        public string printCode { get; set; }
        public string userEIC { get; set; }
    }
}
