//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPApplicationLog
    {
        public int recNo { get; set; }
        public string applicationCode { get; set; }
        public string logDetails { get; set; }
        public string userEIC { get; set; }
        public Nullable<System.DateTime> logDT { get; set; }
    }
}
