//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPAppointmentCasual
    {
        public int recNo { get; set; }
        public string appointmentCode { get; set; }
        public string appointmentName { get; set; }
        public string fundSourceCode { get; set; }
        public string employmentStatusCode { get; set; }
        public string appNatureCode { get; set; }
        public Nullable<System.DateTime> periodFrom { get; set; }
        public Nullable<System.DateTime> periodTo { get; set; }
        public string appType { get; set; }
        public Nullable<System.DateTime> dateIssued { get; set; }
        public string userEIC { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<int> stat { get; set; }
    }
}
