//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPPSBScreeningResult
    {
        public int recNo { get; set; }
        public string applicationCode { get; set; }
        public Nullable<decimal> performanceRating { get; set; }
        public Nullable<decimal> competency { get; set; }
        public Nullable<decimal> BEI { get; set; }
        public Nullable<decimal> psychoTest { get; set; }
        public Nullable<decimal> experience { get; set; }
        public Nullable<decimal> education { get; set; }
        public Nullable<decimal> training { get; set; }
        public Nullable<decimal> eligibility { get; set; }
        public Nullable<decimal> workAccomp { get; set; }
        public Nullable<decimal> totalScore { get; set; }
        public Nullable<int> isSelected { get; set; }
    }
}
