//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPRPTRAIData
    {
        public int recNo { get; set; }
        public string RAICode { get; set; }
        public string batchCode { get; set; }
        public string EIC { get; set; }
        public string appointmentCode { get; set; }
        public string appointmentItemCode { get; set; }
        public Nullable<System.DateTime> dateIssued { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string extnName { get; set; }
        public string middleName { get; set; }
        public string positionTitle { get; set; }
        public string itemNo { get; set; }
        public string salaryGrade { get; set; }
        public Nullable<decimal> salaryRate { get; set; }
        public string employmentStatus { get; set; }
        public string period { get; set; }
        public string natureOfAppointment { get; set; }
        public string publicationPeriod { get; set; }
        public string publicationMode { get; set; }
        public Nullable<int> positionLevel { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
    }
}
