//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPVacantPositionData
    {
        public int recNo { get; set; }
        public string reportCode { get; set; }
        public string plantillaCode { get; set; }
        public string salaryDetailCode { get; set; }
        public Nullable<decimal> rateMonth { get; set; }
        public Nullable<int> separationTag { get; set; }
    }
}
