//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPNOSA
    {
        public int recNo { get; set; }
        public string NOSAId { get; set; }
        public string NOSACode { get; set; }
        public string EIC { get; set; }
        public Nullable<int> itemNo { get; set; }
        public string fullNameFirst { get; set; }
        public string prefixLastName { get; set; }
        public string positionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<decimal> salaryFrom { get; set; }
        public Nullable<decimal> salaryTo { get; set; }
        public Nullable<decimal> salaryAdd { get; set; }
        public string salaryDetailCode { get; set; }
        public string departmentCode { get; set; }
        public string appointmentItemCode { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<System.DateTime> printDT { get; set; }
        public string userEIC { get; set; }
    }
}
