//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPRefFundSource
    {
        public int recNo { get; set; }
        public string fundSourceCode { get; set; }
        public string projectName { get; set; }
        public string remarks { get; set; }
        public string programCode { get; set; }
        public string appropriationCode { get; set; }
        public Nullable<int> hasLimit { get; set; }
        public Nullable<int> isActive { get; set; }
        public string charges { get; set; }
    }
}
