//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPZPlantillaVacant
    {
        public int recNo { get; set; }
        public string printCode { get; set; }
        public Nullable<int> oldItemNo { get; set; }
        public Nullable<int> itemNo { get; set; }
        public string positionTitle { get; set; }
        public string subPositionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public string positionLevel { get; set; }
        public string clusterCode { get; set; }
        public string clusterName { get; set; }
        public string divisionCode { get; set; }
        public string divisionName { get; set; }
        public string sectionCode { get; set; }
        public string sectionName { get; set; }
        public string unitCode { get; set; }
        public string unitName { get; set; }
        public Nullable<int> orderNo { get; set; }
    }
}
