//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPempInfo
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string preffixEng { get; set; }
        public string preffixTitle { get; set; }
        public string suffixTitle { get; set; }
        public string civilStatus { get; set; }
        public string tinNo { get; set; }
        public string bpNo { get; set; }
        public string GSISno { get; set; }
        public string SSSno { get; set; }
        public string pagibigNo { get; set; }
        public string isDisability { get; set; }
        public Nullable<int> issoloParent { get; set; }
        public string ethnicity { get; set; }
        public string PWD { get; set; }
        public string religion { get; set; }
        public string ciitizenship { get; set; }
        public string bloodType { get; set; }
        public Nullable<System.DateTime> LastProm { get; set; }
    }
}
