//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPZServiceRecordTemp
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public string dateTo { get; set; }
        public string designation { get; set; }
        public string empStatus { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string salaryType { get; set; }
        public string office { get; set; }
        public string branch { get; set; }
        public string lwpay { get; set; }
        public string sepCause { get; set; }
        public string remarks { get; set; }
    }
}
