//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPApplicationProfileTraining
    {
        public int recNo { get; set; }
        public string applicationCode { get; set; }
        public Nullable<decimal> hour { get; set; }
        public string trainingTitle { get; set; }
        public Nullable<System.DateTime> periodFrom { get; set; }
        public Nullable<System.DateTime> periodTo { get; set; }
        public string conductedBy { get; set; }
        public string sourceControlNo { get; set; }
    }
}
