//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPNonPlantillaPersonnel
    {
        public int recNo { get; set; }
        public string transCode { get; set; }
        public string appointmentItemCode { get; set; }
        public string salaryDetailCode { get; set; }
        public string remarks { get; set; }
    }
}
