//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPPublication
    {
        public int recNo { get; set; }
        public string publicationCode { get; set; }
        public Nullable<System.DateTime> publicationDate { get; set; }
        public Nullable<System.DateTime> closingDate { get; set; }
        public Nullable<System.DateTime> CSCPostedDate { get; set; }
        public Nullable<System.DateTime> CSCClosingDate { get; set; }
        public string branch { get; set; }
        public string userEIC { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
