//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSALNData
    {
        public int recNo { get; set; }
        public string batchCode { get; set; }
        public string EIC { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middleName { get; set; }
        public string positionTitle { get; set; }
        public Nullable<decimal> networth { get; set; }
        public string spouseRemarks { get; set; }
        public Nullable<int> isJointFiling { get; set; }
        public string departmentCode { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public string userEIC { get; set; }
        public string extName { get; set; }
    }
}
