//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSPMSrefAdjectivalRating
    {
        public int ARcode { get; set; }
        public string ARdetails { get; set; }
        public string ARacronym { get; set; }
    }
}
