//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSysMenuGroup
    {
        public int recNo { get; set; }
        public string menuGroupCode { get; set; }
        public string groupName { get; set; }
        public string fontIcon { get; set; }
        public Nullable<int> groupOrderNo { get; set; }
        public Nullable<int> groupTag { get; set; }
    }
}
