//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSystemEmailLog
    {
        public int recNo { get; set; }
        public string tranCode { get; set; }
        public string controlNo { get; set; }
        public string recepient { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public string messageType { get; set; }
    }
}
