//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSystemLog
    {
        public long recNo { get; set; }
        public string logType { get; set; }
        public string logDetails { get; set; }
        public string EIC { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
    }
}
