//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAttEmpSchemeDaily
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public Nullable<System.DateTime> logDate { get; set; }
        public string schemeCode { get; set; }
        public string schemeName { get; set; }
        public string schemeDetails { get; set; }
        public string in1 { get; set; }
        public string out1 { get; set; }
        public string in2 { get; set; }
        public string out2 { get; set; }
        public Nullable<int> validIn1_minsF { get; set; }
        public Nullable<int> validIn1_minsT { get; set; }
        public Nullable<int> validOut1_minsF { get; set; }
        public Nullable<int> validOut1_minsT { get; set; }
        public Nullable<int> validIn2_minsF { get; set; }
        public Nullable<int> validIn2_minsT { get; set; }
        public Nullable<int> validOut2_minsF { get; set; }
        public Nullable<int> validOut2_minsT { get; set; }
        public Nullable<int> maxLogIn1_minF { get; set; }
        public Nullable<int> maxLogIn1_minT { get; set; }
        public Nullable<int> maxLogOut1_minF { get; set; }
        public Nullable<int> maxLogOut1_minT { get; set; }
        public Nullable<int> maxLogIn2_minF { get; set; }
        public Nullable<int> maxLogIn2_minT { get; set; }
        public Nullable<int> maxLogOut2_minF { get; set; }
        public Nullable<int> maxLogOut2_minT { get; set; }
        public Nullable<int> schemeTypeCode { get; set; }
        public Nullable<int> isActive { get; set; }
        public string userEIC { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
    }
}
