//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLNDToolList
    {
        public string KBICode { get; set; }
        public string MKBICode { get; set; }
        public string KBI { get; set; }
        public string comptCode { get; set; }
        public string comptGroupCode { get; set; }
        public Nullable<int> assessmentYear { get; set; }
        public Nullable<int> orderNo { get; set; }
        public int recNo { get; set; }
    }
}
