//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLNDComptRespondentResult
    {
        public int recNo { get; set; }
        public string respondentCode { get; set; }
        public string comptCode { get; set; }
        public string comptName { get; set; }
        public string comptDesc { get; set; }
        public string comptGroupCode { get; set; }
        public Nullable<int> standard { get; set; }
        public Nullable<decimal> scoreSA { get; set; }
        public Nullable<decimal> scoreDS { get; set; }
        public Nullable<decimal> scoreAve { get; set; }
        public Nullable<int> scoreEqv { get; set; }
    }
}
