//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLNDComptResult
    {
        public int recNo { get; set; }
        public string respondentCode { get; set; }
        public string assessmentCode { get; set; }
        public string assessmentName { get; set; }
        public string assessmentDetail { get; set; }
        public string EIC { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public string positionTitle { get; set; }
        public string supervisorEIC { get; set; }
        public string supervisorName { get; set; }
        public string deptHeadEIC { get; set; }
        public string PGHeadName { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public string departmentCode { get; set; }
        public string shortDepartmentName { get; set; }
        public string departmentName { get; set; }
        public string comptCode { get; set; }
        public string comptName { get; set; }
        public string comptDesc { get; set; }
        public string comptGroupCode { get; set; }
        public Nullable<decimal> aveRate { get; set; }
        public Nullable<int> standardRate { get; set; }
        public Nullable<decimal> rating { get; set; }
        public string remarks { get; set; }
        public string assmntGroupCode { get; set; }
    }
}
