//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLNDCompetencyStandard
    {
        public int recNo { get; set; }
        public string comptPositionCode { get; set; }
        public string comptCode { get; set; }
        public string comptName { get; set; }
        public string comptDesc { get; set; }
        public string comptGroupCode { get; set; }
        public string comptDefinition { get; set; }
        public string comptTool { get; set; }
        public Nullable<int> standardCode { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> assessmentYear { get; set; }
    }
}
