//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLNDSurveyRepondent
    {
        public long recNo { get; set; }
        public string respondentId { get; set; }
        public string EIC { get; set; }
        public string idNo { get; set; }
        public string fullNameLast { get; set; }
        public string positionTitle { get; set; }
        public string departmentCode { get; set; }
        public string departmentName { get; set; }
        public string clusterCode { get; set; }
        public string clusterName { get; set; }
        public string employmentStatus { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public string surveyId { get; set; }
        public int tag { get; set; }
    }
}
