//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLNDCompetencyPositionMap
    {
        public int recNo { get; set; }
        public string plantillaCode { get; set; }
        public string comptPositionCode { get; set; }
        public string comptPositionTitle { get; set; }
        public string comptPositionTitleSub { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public string assmntGroupCode { get; set; }
    }
}
