//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrgStructure
    {
        public int recNo { get; set; }
        public string structureCode { get; set; }
        public string departmentCode { get; set; }
        public string departmentName { get; set; }
        public string shortDepartmentName { get; set; }
        public string clusterCode { get; set; }
        public string clusterName { get; set; }
        public string divisionCode { get; set; }
        public string divisionName { get; set; }
        public string sectionCode { get; set; }
        public string sectionName { get; set; }
        public string unitCode { get; set; }
        public string unitName { get; set; }
        public string parentCode { get; set; }
        public Nullable<int> strucNo { get; set; }
        public Nullable<int> orderNo { get; set; }
        public string branch { get; set; }
        public Nullable<int> deptOrderNo { get; set; }
    }
}
