//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRIMSPlantilla
    {
        public string PlantillaCode { get; set; }
        public string ParentCode { get; set; }
        public string LevelDesc { get; set; }
        public string Accronym { get; set; }
        public string StructureLevelCode { get; set; }
        public Nullable<int> StructureNo { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string PositionCode { get; set; }
        public string SubPositionCode { get; set; }
        public Nullable<decimal> PS { get; set; }
        public Nullable<int> HazardCode { get; set; }
        public Nullable<int> IsFunded { get; set; }
        public string LegendCode { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public string officeCode { get; set; }
        public Nullable<int> RIMS_No { get; set; }
    }
}
