//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPPublicationItemLast
    {
        public int recNo { get; set; }
        public string publicationItemCode { get; set; }
        public string publicationCode { get; set; }
        public string plantillaCode { get; set; }
        public Nullable<System.DateTime> PSBDate { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<System.DateTime> CSCClosingDate { get; set; }
        public Nullable<System.DateTime> CSCPostedDate { get; set; }
    }
}
