//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPEmployeeLatest
    {
        public long recNo { get; set; }
        public string transCode { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public string transType { get; set; }
        public string EIC { get; set; }
        public string plantillaCode { get; set; }
        public string positionCode { get; set; }
        public string positionTitle { get; set; }
        public string subPositionCode { get; set; }
        public string subPositionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public string salaryDetailCode { get; set; }
        public Nullable<decimal> salaryRate { get; set; }
        public string salaryType { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatus { get; set; }
        public string employmentStatusNameShort { get; set; }
        public string employmentStatusTag { get; set; }
        public Nullable<int> isPlantilla { get; set; }
        public Nullable<int> isGovService { get; set; }
        public string appointmentCode { get; set; }
        public string appointmentItemCode { get; set; }
    }
}
