//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPEmployeeCurrentPosition
    {
        public int recNo { get; set; }
        public string transCode { get; set; }
        public string appointmenCode { get; set; }
        public string plantillaCode { get; set; }
        public string EIC { get; set; }
        public string positionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<decimal> rateMonth { get; set; }
        public Nullable<decimal> rateDay { get; set; }
        public string salaryDetailCode { get; set; }
        public string recordTransCode { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatus { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public string subPositionTitle { get; set; }
    }
}
