//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPAppointmentNPP
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string appointmentItemCode { get; set; }
        public string appointmentCode { get; set; }
        public string fundSourceCode { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> PSTag { get; set; }
        public Nullable<int> cy { get; set; }
        public Nullable<int> appointmentTag { get; set; }
    }
}
