//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPRefFundSource
    {
        public string fundSourceCode { get; set; }
        public string projectName { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string programName { get; set; }
        public string programCode { get; set; }
        public string departmentCode { get; set; }
        public string departmentName { get; set; }
        public string approNo { get; set; }
        public Nullable<int> approYear { get; set; }
        public Nullable<int> CY { get; set; }
        public string branch { get; set; }
        public Nullable<int> hasLimit { get; set; }
    }
}
