//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPEmployee
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string idNo { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public string fullNameTitle { get; set; }
        public string namePrefix { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string birthPlace { get; set; }
        public Nullable<System.DateTime> dateOrigAppointment { get; set; }
        public Nullable<System.DateTime> dateLastPromoted { get; set; }
        public string positionCode { get; set; }
        public string subPositionCode { get; set; }
        public string positionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatus { get; set; }
        public string departmentCode { get; set; }
        public string shortDepartmentName { get; set; }
        public string departmentName { get; set; }
        public string workGroupCode { get; set; }
        public string workGroupName { get; set; }
        public string workGroupDesc { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
