//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPPublicationItem
    {
        public string publicationItemCode { get; set; }
        public string plantillaCode { get; set; }
        public Nullable<System.DateTime> publicationDate { get; set; }
        public Nullable<System.DateTime> CSCPostedDate { get; set; }
        public Nullable<System.DateTime> CSCClosingDate { get; set; }
        public Nullable<System.DateTime> PSBDate { get; set; }
        public string publicationCode { get; set; }
        public Nullable<int> itemNo { get; set; }
        public string positionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<decimal> rateMonth { get; set; }
        public string QSEducation { get; set; }
        public string QSExperience { get; set; }
        public string QSTraining { get; set; }
        public string QSEligibility { get; set; }
        public string QSEligibilityPub { get; set; }
        public string QSNotation { get; set; }
        public string departmentName { get; set; }
        public string placeOfAssignment { get; set; }
        public Nullable<int> tag { get; set; }
        public string jobDesc { get; set; }
        public string departmentCode { get; set; }
    }
}
