//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPAppointmentNPEmployee
    {
        public int recNo { get; set; }
        public string appointmentItemCode { get; set; }
        public string EIC { get; set; }
        public string idNo { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public string fullNameTitle { get; set; }
        public string sex { get; set; }
        public string positionCode { get; set; }
        public string positionTitle { get; set; }
        public string shortPositionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public string salaryDetailCode { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string salaryType { get; set; }
        public Nullable<System.DateTime> PSPeriodFrom { get; set; }
        public Nullable<System.DateTime> periodFrom { get; set; }
        public Nullable<System.DateTime> periodTo { get; set; }
        public Nullable<System.DateTime> assumptionDate { get; set; }
        public string fundSourceCode { get; set; }
        public string appointmentName { get; set; }
        public string programName { get; set; }
        public string projectName { get; set; }
        public string appointmentCode { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatusTag { get; set; }
        public string employmentStatus { get; set; }
        public string departmentCode { get; set; }
        public string departmentName { get; set; }
        public string departmentName2 { get; set; }
        public string shortDepartmentName { get; set; }
        public string warmBodyGroupCode { get; set; }
        public string warmBodyGroupName { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<int> empTag { get; set; }
        public Nullable<decimal> PS { get; set; }
        public Nullable<int> CY { get; set; }
        public Nullable<int> PSTag { get; set; }
        public Nullable<decimal> totalPS { get; set; }
        public Nullable<System.DateTime> dateIssued { get; set; }
        public string appNatureCode { get; set; }
        public string appNatureName { get; set; }
        public Nullable<int> positionLevel { get; set; }
        public Nullable<long> postNo { get; set; }
        public string workGroupCode { get; set; }
        public string workGroupName { get; set; }
    }
}
