//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPAppointmentNotify
    {
        public string notificationCode { get; set; }
        public string appointmentItemCode { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public string positionCode { get; set; }
        public string positionTitle { get; set; }
        public string subPositionCode { get; set; }
        public string subPositionTitle { get; set; }
        public string salaryDetailCode { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string salaryType { get; set; }
        public Nullable<System.DateTime> periodFrom { get; set; }
        public Nullable<System.DateTime> periodTo { get; set; }
        public string departmentName { get; set; }
        public string termCode { get; set; }
        public Nullable<System.DateTime> adjstmntFrom { get; set; }
        public Nullable<System.DateTime> adjstmntTo { get; set; }
        public Nullable<int> hasClothing { get; set; }
        public Nullable<int> hasBonusMY { get; set; }
        public Nullable<int> hasBonusYE { get; set; }
        public Nullable<int> hazardCode { get; set; }
        public Nullable<int> tag { get; set; }
        public string fundSourceCode { get; set; }
        public string projectName { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatusNameShort { get; set; }
        public string employmentStatus { get; set; }
        public string employmentStatusTag { get; set; }
        public string remarks { get; set; }
        public string postedByEIC { get; set; }
        public Nullable<System.DateTime> postedDT { get; set; }
    }
}
