//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPPSBApp
    {
        public string appointmentCode { get; set; }
        public string plantillaCode { get; set; }
        public Nullable<int> itemNo { get; set; }
        public string EIC { get; set; }
        public string positionTitle { get; set; }
        public string applicantName { get; set; }
        public string fullNameFirst { get; set; }
        public string fullNameTitle { get; set; }
        public string lastName { get; set; }
        public string namePrefix { get; set; }
        public string departmentName { get; set; }
        public string positionStatusCode { get; set; }
        public string positionStatusName { get; set; }
        public int appTypeCode { get; set; }
        public Nullable<int> recNo { get; set; }
        public Nullable<System.DateTime> psbDate { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
