//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPNONPlantillaPersonnel
    {
        public int recNo { get; set; }
        public string transCode { get; set; }
        public string appointmentItemCode { get; set; }
        public string EIC { get; set; }
        public string positionCode { get; set; }
        public string subPositionCode { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public string positionTitle { get; set; }
        public string shortPositionTitle { get; set; }
        public string acronym { get; set; }
        public string subPositionTitle { get; set; }
        public string subPositionShortTitle { get; set; }
        public string subPositionAcronym { get; set; }
        public string salaryDetailCode { get; set; }
        public string salaryType { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatus { get; set; }
        public Nullable<System.DateTime> periodFrom { get; set; }
        public Nullable<System.DateTime> periodTo { get; set; }
        public Nullable<int> isPlantilla { get; set; }
        public Nullable<int> isGovService { get; set; }
        public string appointmentCode { get; set; }
        public string fundSourceCode { get; set; }
        public string projectName { get; set; }
        public string programName { get; set; }
    }
}
