//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPPSBApplication
    {
        public int recNo { get; set; }
        public string appointmentCode { get; set; }
        public string applicationCode { get; set; }
        public string EIC { get; set; }
        public string applicantCode { get; set; }
        public string applicantName { get; set; }
        public string publicationCode { get; set; }
        public string publicationItemCode { get; set; }
        public string plantillaCode { get; set; }
        public Nullable<int> itemNo { get; set; }
        public string positionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<decimal> rateMonth { get; set; }
        public Nullable<int> appTypeCode { get; set; }
        public Nullable<System.DateTime> CSCPostedDate { get; set; }
        public Nullable<System.DateTime> CSCClosingDate { get; set; }
        public Nullable<System.DateTime> PSBDate { get; set; }
        public Nullable<int> pageNo { get; set; }
    }
}
