//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPAppointmentNonPlantilla
    {
        public int recNo { get; set; }
        public string appointmentCode { get; set; }
        public string appointmentName { get; set; }
        public string projectName { get; set; }
        public string programName { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatus { get; set; }
        public string employmentStatusNameShort { get; set; }
        public Nullable<System.DateTime> periodFrom { get; set; }
        public Nullable<System.DateTime> periodTo { get; set; }
        public Nullable<int> isPlantilla { get; set; }
        public string appNatureName { get; set; }
        public string userEIC { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
        public Nullable<int> tag { get; set; }
        public string departmentCode { get; set; }
        public string departmentName { get; set; }
        public string approNo { get; set; }
        public Nullable<int> approYear { get; set; }
        public Nullable<int> CY { get; set; }
        public Nullable<int> RAIPostNo { get; set; }
        public string fundSourceCode { get; set; }
    }
}
