//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPPublicationVacantForecast
    {
        public int recNo { get; set; }
        public string plantillaCode { get; set; }
        public string EIC { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public Nullable<int> itemNo { get; set; }
        public string positionCode { get; set; }
        public string positionTitle { get; set; }
        public string subPositionCode { get; set; }
        public string subPositionTitle { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public string separationType { get; set; }
        public string remarks { get; set; }
        public string userEIC { get; set; }
        public Nullable<System.DateTime> transDT { get; set; }
    }
}
