//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPPlantillaPrinting
    {
        public int recNo { get; set; }
        public string plantillaCode { get; set; }
        public Nullable<int> oldItemNo { get; set; }
        public Nullable<int> itemNo { get; set; }
        public Nullable<int> newItemNo { get; set; }
        public string structureCode { get; set; }
        public string departmentCode { get; set; }
        public string branch { get; set; }
        public string departmentName { get; set; }
        public string shortDepartmentName { get; set; }
        public string clusterCode { get; set; }
        public string clusterName { get; set; }
        public string divisionCode { get; set; }
        public string divisionName { get; set; }
        public string sectionCode { get; set; }
        public string sectionName { get; set; }
        public string unitCode { get; set; }
        public string unitName { get; set; }
        public string positionCode { get; set; }
        public string positionTitle { get; set; }
        public string shortPositionTitle { get; set; }
        public string subPositionCode { get; set; }
        public string subPositionTitle { get; set; }
        public Nullable<decimal> rateMonth { get; set; }
        public Nullable<int> step { get; set; }
        public string acronym { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> positionLevel { get; set; }
        public string positionLevelName { get; set; }
        public string positionLevelCode { get; set; }
        public Nullable<int> positionCategory { get; set; }
        public Nullable<bool> isFunded { get; set; }
        public string positionStatusCode { get; set; }
        public string positionStatusName { get; set; }
        public Nullable<int> isPlantilla { get; set; }
        public string magnaCode { get; set; }
        public Nullable<int> orderNo { get; set; }
        public string EIC { get; set; }
        public string idNo { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string birthPlace { get; set; }
        public Nullable<System.DateTime> dateOrigAppointment { get; set; }
        public Nullable<System.DateTime> dateLastPromoted { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatus { get; set; }
        public string employmentStatusNameShort { get; set; }
        public string eligibilityCode { get; set; }
        public string eligibilityName { get; set; }
        public string eligibilityNameShort { get; set; }
        public string salaryDetailCode { get; set; }
        public string functionCode { get; set; }
        public Nullable<int> plantillaNo { get; set; }
        public Nullable<int> strucNo { get; set; }
    }
}
