//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPPlantillaPersonnel
    {
        public int recNo { get; set; }
        public string transCode { get; set; }
        public string plantillaCode { get; set; }
        public string appointmenCode { get; set; }
        public string EIC { get; set; }
        public string idNo { get; set; }
        public string fullNameLast { get; set; }
        public Nullable<int> itemNo { get; set; }
        public string positionCode { get; set; }
        public string positionTitle { get; set; }
        public string subPositionCode { get; set; }
        public string subPositionTitle { get; set; }
        public string departmentCode { get; set; }
        public string departmentName { get; set; }
        public string shortDepartmentName { get; set; }
        public string clusterCode { get; set; }
        public string clusterName { get; set; }
        public string divisionCode { get; set; }
        public string divisionName { get; set; }
        public string sectionCode { get; set; }
        public string sectionName { get; set; }
        public string unitCode { get; set; }
        public string unitName { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatus { get; set; }
        public string eligibilityCode { get; set; }
        public string eligibilityName { get; set; }
        public string recordTransCode { get; set; }
        public string salaryDetailCode { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<decimal> rateMonth { get; set; }
        public Nullable<decimal> rateDay { get; set; }
    }
}
