//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPNOSIPropBudYear
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<decimal> propBudgetYear { get; set; }
        public Nullable<int> step { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
