//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPEmployeePlantilla
    {
        public string EIC { get; set; }
        public string idNo { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string positionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatus { get; set; }
        public string shortDepartmentName { get; set; }
        public string departmentName { get; set; }
    }
}
