//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSPAppointmentNPPosted
    {
        public int recNo { get; set; }
        public string appointmentItemCode { get; set; }
        public string EIC { get; set; }
        public string positionCode { get; set; }
        public string positionTitle { get; set; }
        public string subPositionCode { get; set; }
        public string subPositionTitle { get; set; }
        public string employmentStatusCode { get; set; }
        public string employmentStatus { get; set; }
        public string salaryDetailCode { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string salaryType { get; set; }
        public Nullable<System.DateTime> periodFrom { get; set; }
        public Nullable<System.DateTime> periodTo { get; set; }
        public string warmBodyGroupCode { get; set; }
        public string warmBodyGroupName { get; set; }
        public Nullable<int> isDDN { get; set; }
    }
}
