//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDNHRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSalaryTable
    {
        public int recNo { get; set; }
        public string salaryDetailCode { get; set; }
        public string salaryCode { get; set; }
        public Nullable<int> year { get; set; }
        public int salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<decimal> rateMonth { get; set; }
        public Nullable<decimal> rateDay { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
